name: equinet
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiodns=3.5.0=py313haa95532_0
  - aiohappyeyeballs=2.6.1=py313haa95532_0
  - aiohttp=3.12.15=py313h02ab6af_0
  - aiosignal=1.4.0=py313haa95532_0
  - arrow-cpp=19.0.0=h800e9c8_5
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py313haa95532_0
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313h2cb717b_0
  - brotlicffi=1.0.9.2=py313h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py313h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py313haa95532_0
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.13.9=py313hd8ed1ab_101
  - datasets=3.3.2=py313haa95532_0
  - debugpy=1.8.17=py313h927ade5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.3.8=py313haa95532_0
  - et_xmlfile=2.0.0=py313haa95532_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - frozenlist=1.5.0=py313h827c3e9_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - hf-xet=1.1.8=py313h79d111c_0
  - huggingface_hub=0.34.4=py313haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.7=py313haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=py313haa95532_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.15.0=h2300eb9_0
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libmpdec=4.0.0=h827c3e9_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_3
  - libuv=1.48.0=h827c3e9_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.4.0=py313h827c3e9_3
  - mkl_fft=1.3.11=py313h5810407_1
  - mkl_random=1.2.8=py313hedd7022_1
  - multidict=6.1.0=py313h827c3e9_0
  - multiprocess=0.70.15=py313haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.11.0=py313h7660c64_1
  - numpy-base=2.3.3=py313h1e017a8_0
  - openpyxl=3.1.5=py313h827c3e9_1
  - openssl=3.6.0=h725018a_0
  - orc=2.1.1=hd1c1d5c_0
  - packaging=25.0=py313haa95532_0
  - pandas=2.3.2=py313h42c1672_0
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.2=pyhc872135_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py313h827c3e9_0
  - protobuf=5.29.3=py313h5da7b33_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=19.0.0=py313h885b0b7_2
  - pycares=4.10.0=py313he29e43d_0
  - pycparser=2.23=py313haa95532_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py313haa95532_0
  - python=3.13.7=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-gil=3.13.9=h4df99d1_101
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h827c3e9_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313haa95532_0
  - pywin32=311=py313h40c08fc_1
  - pyyaml=6.0.2=py313h827c3e9_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - re2=2024.07.02=h214f63a_0
  - regex=2024.11.6=py313h827c3e9_0
  - requests=2.32.5=py313haa95532_0
  - safetensors=0.5.3=py313hbdb9fe4_0
  - scikit-learn=1.7.1=py313hd8cff78_0
  - scipy=1.16.1=py313hbd6d557_0
  - setuptools=72.1.0=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - threadpoolctl=3.5.0=py313h4442805_0
  - tk=8.6.15=hf199647_0
  - tokenizers=0.21.0=py313hbd09cc8_0
  - tornado=6.5.2=py313h5ea7bf4_2
  - tqdm=4.67.1=py313h4442805_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.49.0=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_0
  - winloop=0.2.2=py313h913537a_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.18.0=py313h827c3e9_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - accelerate==1.10.1
      - annotated-types==0.7.0
      - click==8.3.0
      - filelock==3.13.1
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h5py==3.14.0
      - jieba==0.42.1
      - jinja2==3.1.4
      - jsonlines==4.0.0
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - peft==0.17.1
      - pillow==11.0.0
      - platformdirs==4.4.0
      - psutil==7.1.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - rich==14.1.0
      - sentry-sdk==2.38.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tiktoken==0.11.0
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - trl==0.23.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - ujson==5.11.0
      - wandb==0.22.0
      - wrapt==1.17.3
prefix: C:\Users\hj189\.conda\envs\equinet
